[colors.primary]
background = '#1b202a'
foreground = '#9aa7bd'

[colors.cursor]
text = '#232936'
cursor = '#51617d'

[colors.normal]
black = '#1b202a'
red = '#b15e7c'
green = '#709d6c'
yellow = '#b5a262'
blue = '#608cc3'
magenta = '#8f72bf'
cyan = '#56adb7'
white = '#9aa7bd'

[colors.bright]
black = '#232936'
red = '#b3785d'
green = '#709d6c'
yellow = '#d5b875'
blue = '#608cc3'
magenta = '#c47ebd'
cyan = '#51617d'
white = '#9aa7bd'

[font]
size = 11

[font.bold]
family = "Hack"
style = "Bold"

[font.bold_italic]
family = "Hack"
style = "Bold Italic"

[font.italic]
family = "Hack"
style = "Italic"

[font.normal]
family = "Hack"
style = "Regular"

[font.offset]
x = -1
y = -1

[scrolling]
history = 10000

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
dynamic_padding = true
dynamic_title = true
opacity = 0.8
